# Generated by Django 3.1.3 on 2020-11-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=100, verbose_name='id')),
                ('start_stamp', models.IntegerField()),
                ('end_stamp', models.IntegerField()),
            ],
        ),
    ]
