# Generated by Django 3.1.3 on 2020-11-17 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Example',
            new_name='YoutubeClip',
        ),
    ]
