# Generated by Django 3.1.3 on 2020-11-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_auto_20201117_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeclip',
            name='end_stamp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeclip',
            name='start_stamp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
